"""empty message

Revision ID: 384ac18b5eb6
Revises: 88f165d65057
Create Date: 2020-07-05 01:32:05.817909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '384ac18b5eb6'
down_revision = '88f165d65057'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('capital', sa.Column('rate', sa.String(length=30), nullable=True))
    op.create_foreign_key(None, 'capital', 'loan', ['loan_id'], ['id'])
    op.create_foreign_key(None, 'loan', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'userbill', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'userfund', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userfund', type_='foreignkey')
    op.drop_constraint(None, 'userbill', type_='foreignkey')
    op.drop_constraint(None, 'loan', type_='foreignkey')
    op.drop_constraint(None, 'capital', type_='foreignkey')
    op.drop_column('capital', 'rate')
    # ### end Alembic commands ###
