"""empty message

Revision ID: 88f165d65057
Revises: 
Create Date: 2020-07-04 00:20:15.844996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88f165d65057'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trend',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('loan_name', sa.String(length=30), nullable=True),
    sa.Column('amount', sa.String(length=30), nullable=True),
    sa.Column('balance', sa.String(length=30), nullable=True),
    sa.Column('less_amount', sa.String(length=30), nullable=True),
    sa.Column('amount_rates', sa.String(length=30), nullable=True),
    sa.Column('less_rates', sa.String(length=30), nullable=True, comment='还款利息'),
    sa.Column('balance_rates', sa.String(length=30), nullable=True),
    sa.Column('month', sa.String(length=50), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bank_name', sa.String(length=50), nullable=False),
    sa.Column('loan_name', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.String(length=30), nullable=True),
    sa.Column('balance', sa.String(length=30), nullable=True),
    sa.Column('amount_rates', sa.String(length=30), nullable=True),
    sa.Column('balance_rates', sa.String(length=30), nullable=True),
    sa.Column('rate', sa.String(length=30), nullable=True),
    sa.Column('begin_time', sa.String(length=50), nullable=True),
    sa.Column('end_time', sa.String(length=50), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userbill',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('b_type', sa.String(length=1), nullable=True),
    sa.Column('fund_type', sa.String(length=1), nullable=True),
    sa.Column('number', sa.String(length=20), nullable=True),
    sa.Column('balance', sa.String(length=20), nullable=True),
    sa.Column('memo', sa.String(length=50), nullable=True),
    sa.Column('ref_info', sa.String(length=100), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userfund',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.String(length=30), nullable=True),
    sa.Column('pay_in_ing', sa.String(length=30), nullable=True),
    sa.Column('pay_out_ing', sa.String(length=30), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('capital',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.String(length=30), nullable=True),
    sa.Column('side', sa.String(length=1), nullable=True),
    sa.Column('status', sa.String(length=1), nullable=True),
    sa.Column('expect_time', sa.String(length=50), nullable=True),
    sa.Column('execute_time', sa.String(length=50), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['loan_id'], ['loan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('capital')
    op.drop_table('userfund')
    op.drop_table('userbill')
    op.drop_table('loan')
    op.drop_table('user')
    op.drop_table('trend')
    # ### end Alembic commands ###
